persistence:
  json:
    directory: var/data
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

sessions:
  binance:
    exchange: binance
    envVarPrefix: binance

exchangeStrategies:
  - on: binance
    irr:
      symbol: BTCUSDT
      interval: 5m
      window: 12
      amount: 5000

      # 基础价差设置
      bidSpread: 0.0001 # 默认买入价差 0.01%
      askSpread: 0.0001 # 默认卖出价差 0.01%

      # 动态价差设置
      volatilityAdjustment: true # 启用波动率调整价差
      minSpread: 0.0001 # 最小价差 0.01%
      maxSpread: 0.002 # 最大价差 0.2%

      # 仓位管理
      maxPositionSize: 0.1 # 最大仓位比例 10%
      positionScaling: true # 启用仓位缩放

      # 风险控制
      stopLossPercentage: 0.02 # 止损比例 2%
      takeProfitPercentage: 0.03 # 止盈比例 3%

      # 回测绘图设置
      drawGraph: true
      graphPNLPath: "./pnl.png"
      graphCumPNLPath: "./cumpnl.png"

backtest:
  startTime: "2022-01-01"
  endTime: "2022-11-01"
  symbols:
    - BTCUSDT
  sessions: [binance]
  accounts:
    binance:
      makerFeeRate: 0.0001 # maker 费率 0.01%
      takerFeeRate: 0.0002 # taker 费率 0.02%
      balances:
        BTC: 0.0
        USDT: 5000
